### PR TITLE
chore: upgrade dependency to fix vulnerabilities from npm audit

### PR DESCRIPTION
**Pull request by lanhaoxiang**
upgrade dependency to fix vulnerabilities from npm audit

### CODE REVIEW

**Comment by nsjames** [comment]
This extension is not being maintained anymore, and has been deprecated for a few months right now. 
It should not be used.

**Comment by lanhaoxiang** [comment]
@nsjames Thanks for the notice.

However in my view,  this project is very powerful and well designed, it's different from the desktop app, it also becomes a standard protocol design in a lot of mobile app, just like meet.one and token pocket. 

Can you show me the reasons why the team giving up this project?

**Comment by lanhaoxiang** [comment]
OK, I missed it :( 

https://medium.com/getscatter/the-blockchain-isnt-just-for-web-applications-silly-rabbit-926a4ea5ccd1

**Comment by nsjames** [comment]
Yup that article lays it out pretty well.

**Comment by lanhaoxiang** [comment]
Cool solution, fuck chrome

**Pull request closed without merging**
